// src/providers/copilot.js
import path from "node:path";
import fs from "node:fs/promises";
import { ensureDir } from "../utils.js";

/**
 * Provider for GitHub Copilot repository instructions
 * Generates a single `.github/copilot-instructions.md` file that aggregates rules
 * @implements {import("../types.js").RuleProvider}
 */
export class CopilotProvider {
  /**
   * @readonly
   * @type {string}
   */
  id = "copilot";

  /**
   * @private
   * @type {string}
   */
  #outFile = path.resolve(".github/copilot-instructions.md");

  /**
   * @private
   * @type {string}
   */
  #buffer = "";

  /**
   * Prepare output file and ensure directory exists
   * @returns {Promise<void>}
   */
  async init() {
    await ensureDir(path.dirname(this.#outFile));
    await fs.rm(this.#outFile, { force: true });
  }

  /**
   * Convert a rule file to a Copilot-friendly section and append to buffer
   * Provider-specific overrides can be placed under `copilot:` in the YAML
   * @param {import("../types.js").RuleFileInput} file
   * @returns {Promise<void>}
   */
  async handle({ frontMatter, content }) {
    const yaml = { ...frontMatter, ...(frontMatter.copilot ?? {}) };
    const sectionTitle = yaml.title ?? yaml.description ?? "Untitled";
    this.#buffer += `\n\n## ${sectionTitle}\n\n${content.trim()}\n`;
  }

  /**
   * Write the aggregated instructions file
   * @returns {Promise<void>}
   */
  async finish() {
    const header =
      `# Copilot Repository Instructions\n\n` + `<!-- Generated by agent-rules. Do not edit this file manually. -->\n`;
    const output = (header + this.#buffer).trimEnd() + "\n";
    await fs.writeFile(this.#outFile, output, "utf8");
  }
}
